spring.application.name=Gruppuppgift6A
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/book
spring.datasource.username=postgres
spring.datasource.password=password
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/Book
spring.datasource.username=postgres
spring.datasource.password=randomfuckingpassword
>>>>>>> 246500f73d4c63655f4a438359824cc64e86e2bb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect